name: Web App CI
on:
  pull_request: 
    branches:
      - main
      - master
    paths:
      - "machine-learing-client/**"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      working-directory: ./machine-learning-client
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Make pipenv editable
        run: |
          pipenv install -e --dev .
      - name: Test with pytest
        run: |
          pipenv --venv
          pipenv run python -m pytest
    