name: Machine Learning Client CI

on:
  push:
    paths:
      - 'machine-learning-client/**'
      - '.github/workflows/ml-client-ci.yml'
  pull_request:
    paths:
      - 'machine-learning-client/**'
      - '.github/workflows/ml-client-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          cd machine-learning-client
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run linter
        run: |
          cd machine-learning-client
          pylint --fail-under=8.0 main.py test_main.py
          
      - name: Run formatter
        run: |
          cd machine-learning-client
          black --check main.py test_main.py
          
      - name: Run tests with coverage
        run: |
          cd machine-learning-client
          pytest --cov=main test_main.py --cov-report=xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./machine-learning-client/coverage.xml
          fail_ci_if_error: true 