name: Web App CI

on:
  push:
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app-ci.yml'
  pull_request:
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          cd web-app
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run linter
        run: |
          cd web-app
          pylint --fail-under=8.0 app.py test_app.py
          
      - name: Run formatter
        run: |
          cd web-app
          black --check app.py test_app.py
          
      - name: Run tests with coverage
        run: |
          cd web-app
          pytest --cov=app test_app.py --cov-report=xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./web-app/coverage.xml
          fail_ci_if_error: true 